let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car !== 'subaru'? I predict True.");
console.log(car !== 'subaru');
console.log("Is car == 'Ford'? I predict True.");
console.log(car == 'Ford');
console.log("Is car !== 'Ford'? I predict True.");
console.log(car !== 'Ford');
console.log("Is car == 'BMW'? I predict True.");
console.log(car == 'BMW');
console.log("Is car !== 'BMW'? I predict True.");
console.log(car !== 'BMW');
console.log("Is car == 'Toyota'? I predict True.");
console.log(car == 'Toyota');
console.log("Is car !== 'Toyota'? I predict True.");
console.log(car !== 'Toyota');
console.log("Is car == 'Aulto'? I predict True.");
console.log(car == 'Aulto');
console.log("Is car !== 'Aulto'? I predict True.");
console.log(car !== 'Aulto');